title: Erick Ruiz de Chavez
email: erick@erch.co
# description: > # this means to ignore newlines until "baseurl:"
#   Lorem ipsum dolor sit amet, consectetur adipisicing elit, 
#   sed do eiusmod tempor incididunt ut labore et dolore magna 
#   aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
#   ullamco laboris nisi ut aliquip ex ea commodo consequat. 
#   Duis aute irure dolor in reprehenderit in voluptate velit 
#   esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
#   occaecat cupidatat non proident, sunt in culpa qui officia 
#   deserunt mollit anim id est laborum.
baseurl: ""
url: "http://erickruizdechavez.com"
permalink: /:year-:month-:day-:title.html
lang: es
date_format: "%e de %B del %Y"

excerpt_separator: <!--more-->

twitter_username: eruizdechavez
github_username:  eruizdechavez
github_projectname: erickruizdechavez.com

minify_html: true
markdown: kramdown
gems:
  - jekyll-feed

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: page
  -
    scope:
      type: "posts"
    values:
      layout: post
      author: Erick
